### ISSUE TITLE
Great package! Why not register it?

### ISSUE THREAD

**Issue by svilupp** [astariul/Sentencize.jl#5]
Thank you for the package! I've tried to build something similar with regex but your package seems to work well enough.

Why have you not registered it? It would make it much more convenient to include it as a registered dependency.

**Comment by astariul** [comment]
Hey @svilupp, thanks for your comment.

To be honest, I wrote this package when I was trying to learn Julia. I haven't touched Julia in a while, I don't know how to register package.

Is it something you know how to do ? Would you be interested in opening a PR ?

Ideally we would have a github actions that publish this package on every release.

**Comment by svilupp** [comment]
Sure. Give me a few days and I'll do it in a PR.
